### ISSUE TITLE
Change Unique Ids from UUID to Longs

### ISSUE THREAD

**Issue by sophiacrennan** [sandboxnu/pharmd-tracker-backend#47]
**Problem**: UUID can be a pain and are unnecessary 
**Solution**: change UUIDs to unique longs

**Description**: We don't necessarily need UUID for our unique ids and causes problems so why not change it to longs to make our lives easier

**Specs:**
- [ ] change all UUIDs to unique longs

If blocked, contact @nicolesorial @VKong6019

**Comment by VKong6019** [comment]
>Note about bigint type: bigint column type, used in SQL databases, doesn't fit into the regular number type and maps property to a string instead.

~lol javascript doesn't like long/bigint, pain~

it works and that the docs are lying to me :(
